FROM golang:1.15-buster AS gobuild

COPY .  /go/src/github.com/koestler/go-image-server/
WORKDIR /go/src/github.com/koestler/go-image-server/

RUN go get -v
RUN ./build.sh
RUN mv go-image-server /go/bin/go-image-server

FROM scratch
EXPOSE 80/tcp
COPY --from=gobuild /go/bin/go-image-server /go-image-server
ENTRYPOINT ["/go-image-server"]
